package com.opd.dtox;

import android.app.Activity;
import android.os.Bundle;
import android.view.WindowManager;

// EbitenView is generated by ebitenmobile bind into the go.mobile Java package.
import go.mobile.EbitenView;

/**
 * MainActivity bootstraps the Ebitengine game produced by ebitenmobile bind.
 *
 * The EbitenView class is provided by the tox-gui.aar library (built from
 * ./mobile/mobile.go via `ebitenmobile bind -target android -javapkg go`).
 * It hosts the OpenGL surface and handles all input forwarding to Go.
 */
public class MainActivity extends Activity {

    private EbitenView ebitenView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Keep the screen on while the game is running.
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        ebitenView = new EbitenView(this);
        setContentView(ebitenView);
    }

    @Override
    protected void onPause() {
        super.onPause();
        ebitenView.suspendGame();
    }

    @Override
    protected void onResume() {
        super.onResume();
        ebitenView.resumeGame();
    }
}
